lua require('my_plugins')
lua require("bufferline").setup{}
lua require('tree_sitter')
source ~/.config/nvim/configs/autocmds.vim
source ~/.config/nvim/configs/keybinds.vim
source ~/.config/nvim/configs/lsp.vim
source ~/.config/nvim/configs/airline.vim
source ~/.config/nvim/configs/fzf.vim
source ~/.config/nvim/configs/colors.vim
source ~/.config/nvim/configs/envs.vim
