lua require('my_plugins')
lua require("bufferline").setup{}
source ./configs/autocmds.vim
source ./configs/keybinds.vim
source ./configs/lsp.vim
source ./configs/airline.vim
source ./configs/fzf.vim
source ./configs/colors.vim
source ./configs/envs.vim
